package workspacecli

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	ZDOTDirEnv         = "ZDOTDIR"
	OriginalZDOTDirEnv = "LUMI_ORIGINAL_ZDOTDIR"
	ManagedZDOTDirEnv  = "LUMI_MANAGED_ZDOTDIR"
)

var zshStartupFiles = []string{".zshenv", ".zprofile", ".zshrc", ".zlogin"}

func UsesZsh(shell string) bool {
	shell = strings.TrimSpace(shell)
	if shell == "" {
		return false
	}
	if fields := strings.Fields(shell); len(fields) > 0 {
		shell = fields[0]
	}
	shell = strings.ReplaceAll(shell, `\`, "/")
	return strings.EqualFold(strings.TrimSuffix(filepath.Base(shell), ".exe"), "zsh")
}

func ConfigureZshStartupEnv(env map[string]string, bridgeRoot, shell, requiredPath string) error {
	if env == nil {
		return fmt.Errorf("Agent environment is required")
	}

	originalZDOTDir, restored := restoreOriginalZDOTDir(env, bridgeRoot)
	if !UsesZsh(shell) || strings.TrimSpace(requiredPath) == "" {
		return nil
	}
	if !restored {
		originalZDOTDir = effectiveEnv(env, ZDOTDirEnv)
		if IsManagedZDOTDir(originalZDOTDir, bridgeRoot) {
			originalZDOTDir = effectiveEnv(env, OriginalZDOTDirEnv)
		}
	}

	bridge, err := PrepareZshStartupBridge(bridgeRoot, originalZDOTDir, requiredPath)
	if err != nil {
		return err
	}
	env[OriginalZDOTDirEnv] = originalZDOTDir
	env[ManagedZDOTDirEnv] = bridge
	env[ZDOTDirEnv] = bridge
	return nil
}

func PrepareZshStartupBridge(root, sourceDir, requiredPath string) (string, error) {
	root = strings.TrimSpace(root)
	requiredPath = strings.TrimSpace(requiredPath)
	if root == "" {
		return "", fmt.Errorf("zsh startup bridge root is required")
	}
	if requiredPath == "" {
		return "", fmt.Errorf("required PATH entry is required")
	}

	sum := sha256.Sum256([]byte(filepath.Clean(sourceDir) + "\x00" + filepath.Clean(requiredPath)))
	bridge := filepath.Join(root, fmt.Sprintf("%x", sum[:12]))
	if err := os.MkdirAll(bridge, 0o700); err != nil {
		return "", fmt.Errorf("create zsh startup bridge: %w", err)
	}
	if err := os.Chmod(bridge, 0o700); err != nil {
		return "", fmt.Errorf("secure zsh startup bridge: %w", err)
	}

	for _, name := range zshStartupFiles {
		content := zshStartupBridgeFile(name, sourceDir, requiredPath)
		if err := writeFileAtomically(filepath.Join(bridge, name), []byte(content), 0o600); err != nil {
			return "", fmt.Errorf("write zsh startup bridge %s: %w", name, err)
		}
	}
	return bridge, nil
}

func IsManagedZDOTDir(path, root string) bool {
	path = strings.TrimSpace(path)
	root = strings.TrimSpace(root)
	if path == "" || root == "" {
		return false
	}
	rel, err := filepath.Rel(filepath.Clean(root), filepath.Clean(path))
	return err == nil && rel != "." && rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator))
}

func restoreOriginalZDOTDir(env map[string]string, bridgeRoot string) (string, bool) {
	managed := effectiveEnv(env, ManagedZDOTDirEnv)
	current := effectiveEnv(env, ZDOTDirEnv)
	if managed == "" && !IsManagedZDOTDir(current, bridgeRoot) {
		return "", false
	}

	original := effectiveEnv(env, OriginalZDOTDirEnv)
	if original == "" {
		delete(env, ZDOTDirEnv)
	} else {
		env[ZDOTDirEnv] = original
	}
	delete(env, OriginalZDOTDirEnv)
	delete(env, ManagedZDOTDirEnv)
	return original, true
}

func effectiveEnv(env map[string]string, key string) string {
	if value, ok := env[key]; ok {
		return strings.TrimSpace(value)
	}
	return strings.TrimSpace(os.Getenv(key))
}

func zshStartupBridgeFile(name, sourceDir, requiredPath string) string {
	return fmt.Sprintf(`# Generated by Lumi. Changes will be overwritten.
_lumi_source_dir=%s
_lumi_required_path=%s
if [[ -n "$_lumi_source_dir" ]]; then
  _lumi_startup_file="$_lumi_source_dir/%s"
else
  _lumi_startup_file="$HOME/%s"
fi
if [[ -r "$_lumi_startup_file" ]]; then
  _lumi_bridge_zdotdir="$ZDOTDIR"
  if [[ -n "$_lumi_source_dir" ]]; then
    export ZDOTDIR="$_lumi_source_dir"
  else
    unset ZDOTDIR
  fi
  source "$_lumi_startup_file"
  export ZDOTDIR="$_lumi_bridge_zdotdir"
fi
typeset -gaU path
path=("$_lumi_required_path" $path)
unset _lumi_bridge_zdotdir _lumi_required_path _lumi_source_dir _lumi_startup_file
`, shellQuote(sourceDir), shellQuote(requiredPath), name, name)
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}

func writeFileAtomically(path string, data []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	file, err := os.CreateTemp(dir, "."+filepath.Base(path)+".tmp-*")
	if err != nil {
		return err
	}
	tempPath := file.Name()
	defer os.Remove(tempPath)

	if err := file.Chmod(mode); err != nil {
		file.Close()
		return err
	}
	if _, err := file.Write(data); err != nil {
		file.Close()
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}
	return os.Rename(tempPath, path)
}
